import { useState } from "react";
import { useListStories, useCreateStory, useUpdateStory, useDeleteStory, useGenerateStoryContent, getListStoriesQueryKey } from "@workspace/api-client-react";
import { useQueryClient } from "@tanstack/react-query";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Badge } from "@/components/ui/badge";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Search, Plus, Edit, Trash2, Wand2, Star, Check, X } from "lucide-react";
import { toast } from "sonner";

export default function AdminStories() {
  const queryClient = useQueryClient();
  const [page, setPage] = useState(1);
  const [search, setSearch] = useState("");
  const [isCreateOpen, setIsCreateOpen] = useState(false);
  const [generatingFor, setGeneratingFor] = useState<number | null>(null);

  const { data, isLoading } = useListStories({ page, limit: 10 });

  const createStory = useCreateStory();
  const updateStory = useUpdateStory();
  const deleteStory = useDeleteStory();
  const generateStory = useGenerateStoryContent();

  const [formData, setFormData] = useState({
    title: "",
    description: "",
    levelNumber: 1,
    category: "fantasy",
    difficulty: "medium" as any,
    coinsReward: 100,
    gemsReward: 10,
    xpReward: 50,
    estimatedMinutes: 5,
    isPremium: false
  });

  const handleCreate = () => {
    createStory.mutate({ data: formData }, {
      onSuccess: () => {
        queryClient.invalidateQueries({ queryKey: getListStoriesQueryKey() });
        setIsCreateOpen(false);
        toast.success("Story level created");
      },
      onError: () => toast.error("Failed to create story")
    });
  };

  const handleTogglePublish = (story: any) => {
    updateStory.mutate({ id: story.id, data: { isPublished: !story.isPublished } }, {
      onSuccess: () => {
        queryClient.invalidateQueries({ queryKey: getListStoriesQueryKey() });
        toast.success(story.isPublished ? "Story unpublished" : "Story published");
      }
    });
  };

  const handleDelete = (id: number) => {
    if (!confirm("Are you sure you want to delete this story?")) return;
    deleteStory.mutate({ id }, {
      onSuccess: () => {
        queryClient.invalidateQueries({ queryKey: getListStoriesQueryKey() });
        toast.success("Story deleted");
      }
    });
  };

  const handleGenerate = (id: number) => {
    setGeneratingFor(id);
    generateStory.mutate({ id }, {
      onSuccess: () => {
        setGeneratingFor(null);
        queryClient.invalidateQueries({ queryKey: getListStoriesQueryKey() });
        toast.success("Story content generated by AI!");
      },
      onError: () => {
        setGeneratingFor(null);
        toast.error("Failed to generate story content");
      }
    });
  };

  return (
    <div className="space-y-6">
      <div className="flex justify-between items-center mb-6">
        <h1 className="text-3xl font-bold text-foreground">Stories Management</h1>
        
        <Dialog open={isCreateOpen} onOpenChange={setIsCreateOpen}>
          <DialogTrigger asChild>
            <Button><Plus className="w-4 h-4 mr-2" /> New Level</Button>
          </DialogTrigger>
          <DialogContent className="max-w-2xl max-h-[90vh] overflow-y-auto">
            <DialogHeader>
              <DialogTitle>Create New Story Level</DialogTitle>
            </DialogHeader>
            <div className="grid grid-cols-2 gap-4 py-4">
              <div className="space-y-2 col-span-2">
                <Label>Title</Label>
                <Input value={formData.title} onChange={e => setFormData({...formData, title: e.target.value})} />
              </div>
              <div className="space-y-2 col-span-2">
                <Label>Description</Label>
                <Textarea value={formData.description} onChange={e => setFormData({...formData, description: e.target.value})} />
              </div>
              <div className="space-y-2">
                <Label>Level Number</Label>
                <Input type="number" value={formData.levelNumber} onChange={e => setFormData({...formData, levelNumber: parseInt(e.target.value)})} />
              </div>
              <div className="space-y-2">
                <Label>Category</Label>
                <Input value={formData.category} onChange={e => setFormData({...formData, category: e.target.value})} />
              </div>
              <div className="space-y-2">
                <Label>Difficulty</Label>
                <Select value={formData.difficulty} onValueChange={(v: any) => setFormData({...formData, difficulty: v})}>
                  <SelectTrigger><SelectValue /></SelectTrigger>
                  <SelectContent>
                    <SelectItem value="easy">Easy</SelectItem>
                    <SelectItem value="medium">Medium</SelectItem>
                    <SelectItem value="hard">Hard</SelectItem>
                    <SelectItem value="legendary">Legendary</SelectItem>
                  </SelectContent>
                </Select>
              </div>
              <div className="space-y-2">
                <Label>Estimated Minutes</Label>
                <Input type="number" value={formData.estimatedMinutes} onChange={e => setFormData({...formData, estimatedMinutes: parseInt(e.target.value)})} />
              </div>
              <div className="space-y-2">
                <Label>Coins Reward</Label>
                <Input type="number" value={formData.coinsReward} onChange={e => setFormData({...formData, coinsReward: parseInt(e.target.value)})} />
              </div>
              <div className="space-y-2">
                <Label>Gems Reward</Label>
                <Input type="number" value={formData.gemsReward} onChange={e => setFormData({...formData, gemsReward: parseInt(e.target.value)})} />
              </div>
              <div className="space-y-2">
                <Label>XP Reward</Label>
                <Input type="number" value={formData.xpReward} onChange={e => setFormData({...formData, xpReward: parseInt(e.target.value)})} />
              </div>
              <div className="space-y-2 flex items-center pt-8 gap-2">
                <input 
                  type="checkbox" 
                  id="isPremium" 
                  checked={formData.isPremium} 
                  onChange={e => setFormData({...formData, isPremium: e.target.checked})} 
                  className="w-4 h-4"
                />
                <Label htmlFor="isPremium">Premium Only</Label>
              </div>
              <Button onClick={handleCreate} disabled={createStory.isPending} className="col-span-2 mt-4">
                Create Story Level
              </Button>
            </div>
          </DialogContent>
        </Dialog>
      </div>

      <Card className="p-4 bg-card border-border">
        <div className="rounded-md border border-border">
          <Table>
            <TableHeader>
              <TableRow className="border-border">
                <TableHead>Level</TableHead>
                <TableHead>Story</TableHead>
                <TableHead>Rewards</TableHead>
                <TableHead>Status</TableHead>
                <TableHead>Content</TableHead>
                <TableHead className="text-right">Actions</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {isLoading ? (
                <TableRow>
                  <TableCell colSpan={6} className="text-center py-8">Loading...</TableCell>
                </TableRow>
              ) : data?.stories.map((story: any) => (
                <TableRow key={story.id} className="border-border">
                  <TableCell className="font-bold text-lg">{story.levelNumber}</TableCell>
                  <TableCell>
                    <div className="font-medium flex items-center gap-2">
                      {story.title}
                      {story.isPremium && <Star className="w-3 h-3 text-purple-400 fill-current" />}
                    </div>
                    <div className="text-xs text-muted-foreground flex gap-2">
                      <span>{story.category}</span>
                      <span>•</span>
                      <span className="capitalize">{story.difficulty}</span>
                    </div>
                  </TableCell>
                  <TableCell>
                    <div className="flex gap-2 text-xs">
                      <span className="text-yellow-400 font-medium">🪙 {story.coinsReward}</span>
                      <span className="text-purple-400 font-medium">💎 {story.gemsReward}</span>
                    </div>
                  </TableCell>
                  <TableCell>
                    <Badge variant="outline" className={story.isPublished ? 'bg-green-500/10 text-green-400' : 'bg-muted text-muted-foreground'}>
                      {story.isPublished ? 'Published' : 'Draft'}
                    </Badge>
                  </TableCell>
                  <TableCell>
                    {story.storyContent ? (
                      <Badge variant="outline" className="bg-blue-500/10 text-blue-400 border-blue-500/20">
                        <Check className="w-3 h-3 mr-1" /> Generated
                      </Badge>
                    ) : (
                      <Badge variant="outline" className="bg-orange-500/10 text-orange-400 border-orange-500/20">
                        <X className="w-3 h-3 mr-1" /> Missing
                      </Badge>
                    )}
                  </TableCell>
                  <TableCell className="text-right">
                    <div className="flex justify-end gap-2">
                      <Button 
                        variant="outline" 
                        size="icon"
                        title="Generate AI Content"
                        onClick={() => handleGenerate(story.id)}
                        disabled={generatingFor === story.id || generateStory.isPending}
                        className={!story.storyContent ? "border-primary text-primary" : ""}
                      >
                        {generatingFor === story.id ? <div className="w-4 h-4 border-2 border-primary border-t-transparent rounded-full animate-spin" /> : <Wand2 className="w-4 h-4" />}
                      </Button>
                      <Button 
                        variant="outline" 
                        size="sm"
                        onClick={() => handleTogglePublish(story)}
                        disabled={updateStory.isPending || (!story.storyContent && !story.isPublished)}
                      >
                        {story.isPublished ? "Unpublish" : "Publish"}
                      </Button>
                      <Button variant="destructive" size="icon" onClick={() => handleDelete(story.id)}>
                        <Trash2 className="w-4 h-4" />
                      </Button>
                    </div>
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </div>
      </Card>
    </div>
  );
}
